### ISSUE TITLE
some warning!!!

### ISSUE THREAD

**Issue by Hmissa** [nRF24/RF24Network#128]
RF24Network.cpp file:
- in line 606: the function return -1 but in the definition the result type is unsigned.
- in line 698: you have an assignement in condition!!
- in line 1238: digit is unsigned but you compare it with 0.

Best Regards,
Saif.

**Comment by kolaha99** [comment]
helloworld_rx.ino
C:\Arduino Scetches\libraries\RF24Network\examples\helloworld_rx

C:\Arduino Scetches\libraries\RF24Network\RF24Network.cpp: In member function 'uint8_t RF24Network::enqueue(RF24NetworkHeader*)':

C:\Arduino Scetches\libraries\RF24Network\RF24Network.cpp:534:56: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

         if(MAX_PAYLOAD_SIZE - (next_frame-frame_queue) >= frag_queue.message_size){

C:\Arduino Scetches\libraries\RF24Network\RF24Network.cpp: In member function 'uint16_t RF24Network::read(RF24NetworkHeader&, void*, uint16_t)':

C:\Arduino Scetches\libraries\RF24Network\RF24Network.cpp:694:12: error: 'rf24_min' was not declared in this scope

   maxlen = rf24_min(maxlen,bufsize);

            ^~~~~~~~

C:\Arduino Scetches\libraries\RF24Network\RF24Network.cpp:694:12: note: suggested alternative: 'fmin'

   maxlen = rf24_min(maxlen,bufsize);

            ^~~~~~~~

            fmin

C:\Arduino Scetches\libraries\RF24Network\RF24Network.cpp: In member function 'bool RF24Network::write(RF24NetworkHeader&, const void*, uint16_t, uint16_t)':

C:\Arduino Scetches\libraries\RF24Network\RF24Network.cpp:794:25: error: 'rf24_min' was not declared in this scope

  uint16_t fragmentLen = rf24_min((uint16_t)(len-offset),max_frame_payload_size);

                         ^~~~~~~~

C:\Arduino Scetches\libraries\RF24Network\RF24Network.cpp:794:25: note: suggested alternative: 'fmin'

  uint16_t fragmentLen = rf24_min((uint16_t)(len-offset),max_frame_payload_size);

                         ^~~~~~~~

                         fmin

C:\Arduino Scetches\libraries\RF24Network\RF24Network.cpp: In member function 'bool RF24Network::is_valid_address(uint16_t)':

C:\Arduino Scetches\libraries\RF24Network\RF24Network.cpp:1245:12: warning: comparison is always false due to limited range of data type [-Wtype-limits]

  if (digit < 0 || digit > 5) //Allow our out of range multicast address

      ~~~~~~^~~

exit status 1
Fehler beim Kompilieren für das Board Arduino Uno.
