### ISSUE TITLE
No module named RF 24 

### ISSUE THREAD

**Issue by vamsikrishnaA9** [nRF24/RF24Network#135]
@TMRh20  dear sir Python wrapper is not installing properly. I am using raspberry pi 3B+. When i run the helloworld-tx.py it is showing no module named RF24.
Please help i think 3,4 commands http://tmrh20.github.io/RF24/Python.html
In the above link i couldn’t find path for them. Thank u

**Comment by 2bndy5** [comment]
The [python wrapper installation instructions have been updated](https://github.com/nRF24/RF24/issues/615#issuecomment-671525320) since this issue was raised. Please try again with updated instructions. Please keep in mind that the python wrapper installs the RF24 library and the RF24Network library as a separate python packages. HINT: Use `pip3 list` to determine if the RF24 and RF24Network packages are indeed installed.
