### ISSUE TITLE
How to reduce power with Nrf24l01 network

### ISSUE THREAD

**Issue by mixaobo** [nRF24/RF24Network#142]
i read ping_sleepy in Nrf24l01 and nrf24l01network.
In nrf24l01 library, i see you use powerDown (CE = 0) and powerUp to put nrf24l01 in standby mode.
but i have confuse why dont you use powerDown and powerUp in nrf24l01network? 
(i'm using esp32 and use deep sleep)

**Comment by 2bndy5** [comment]
There is no way to wirelessly invoke waking up the nRF24L01 as "power down" mode (controlled via `powerUp()` & `powerDown()`) kills all reception and transmission to save current draw. The ESB protocol (underlying mechanism in the nRF24L01 firmware) is in "StandBy-I" mode when idling, and it usually falls back to "StandBy-II" mode when TX FIFO is exhausted or blocked due to failure of receiving an ACK packet during transmission. Both nRF24L01 "StandBy-x" modes were carefully designed with minimal current draw in mind (according to the datasheet). For more information on current consumption, [see the table 4 in section 5.1 of the datasheet](https://www.sparkfun.com/datasheets/Components/SMD/nRF24L01Pluss_Preliminary_Product_Specification_v1_0.pdf#G1120559). More information about the different nRF24L01 operating modes can be found in [section 6.1 of the datasheet](https://www.sparkfun.com/datasheets/Components/SMD/nRF24L01Pluss_Preliminary_Product_Specification_v1_0.pdf#G1132278)

This RF24Network library is rather high level. Thus, it is better left to the application programmer to manage the RF24 libraries lower level `powerUp()` & `powerDown()` functions when applicable. The RF24Network library's [`sleepNode()`](http://tmrh20.github.io/RF24Network/classRF24Network.html#acc3e7809ffc7ff48579811d2e063142a) is uses network pings as an attempt to emulate the "deep sleep" functionality of the ESP32, but the nRF24L01 doesn't have a convenient ULP co-processor like the ESP32 uses for "deep sleep". I hope I explained this right.
