### ISSUE TITLE
Is it possible to work this library with Node Red?

### ISSUE THREAD

**Issue by potier97** [nRF24/RF24Network#159]
Hello, is there a way to integrate these libraries with NodeRed and do the integration for the RF24?

Thank you.

**Comment by TMRh20** [comment]
I remember looking at this before sometime... It looks like somebody is/has been working on it. Hasn't been updated in a while, but some action on GitHub:
https://flows.nodered.org/node/node-red-contrib-nrf24
https://github.com/ludiazv/node-nrf24

It mentions basic RF24 communication along with RF24Mesh, RF24Ethernet and RF24Gateway, but doesn't specifically mention RF24Network. I would assume RF24Network might be a bit of a hassle to get into Node Red compared to RF24Mesh, since its more complicated to configure the network manually. I assume that would be your best bet as a starting point.

I don't have any current plans to expand the scope of this lib beyond C++ and the Python wrapper myself, but definitely willing to support/assist/accommodate those wanting to do so.
