### ISSUE TITLE
Set Base Node 00 (sersornet example)

### ISSUE THREAD

**Issue by bobibob77** [nRF24/RF24Network#25]
I have trouble to set node 0 to test sesornet example.

Do you have any hint how to do that.

Here is an issue opened in maniacbug library:
https://github.com/maniacbug/RF24Network/issues/13

Because this is fork which is developed further i try to get answer here.
Arduino forum is under maintenance :(

It would be very nice to get any instructions how to set master node to 000.

If I try to set it in sesornet example
I get message:
"This sketch cannot run on node 00"

On forum was said that for this I need another sketch, but I can't find any.
Thank you for your help if it's possible.

**Comment by thakursaajid** [comment]
Dear Sir,
There is "Two different nRF24 set is **Overlapping signals** if put same node 00, nade 01 and so on" 
for example, there are two sets of nRF24Network.
Using first set for temperature transmitter as using master node 00, transmitter node 01.
and second set for temperature transmitter as using also master node 00, transmitter node 01.
is there any solution or a different address that can replace by nodes?
For example: Master node 00 = 0xF0F0F0F0AA
                         Slave node 01= 0xF0F0F0F0BB

**Comment by 2bndy5** [comment]
This library is not designed to have more than 1 master node (or 2 networks) all on the same channel.
You have 2 options:
1. Use a different channel for each network. This option may not be what you want because data will not be passed between different networks.
2. Use more unique node addresses (01, 011, 02, 012) and filter the messages at the master node based on message type. The [Priority_RX](https://github.com/nRF24/RF24Network/tree/master/examples/Network_Priority_RX) and [Prioity_TX](https://github.com/nRF24/RF24Network/tree/master/examples/Network_Priority_TX) examples should get you started with this option.
   - You could also filter messages based on what branch they originate from. Say all children of node 01 provide temperature data, and all children of node 02 provide humidity.
 
Ultimately, you don't want to mess with the pipe addresses on network nodes because that's simply not how the library was designed.

**Comment by thakursaajid** [comment]
Supper, It worked.
Thanks, Sir.
I used your Idea and made two numbers of nRFnetwork set communicate with BMS, also use two different unique to be sent.
▬▬

> This library is not designed to have more than 1 master node (or 2 networks) all on the same channel. You have 2 options:
> 
> 1. Use a different channel for each network. This option may not be what you want because data will not be passed between different networks.
> 2. Use more unique node addresses (01, 011, 02, 012) and filter the messages at the master node based on message type. The [Priority_RX](https://github.com/nRF24/RF24Network/tree/master/examples/Network_Priority_RX) and [Prioity_TX](https://github.com/nRF24/RF24Network/tree/master/examples/Network_Priority_TX) examples should get you started with this option.
>    
>    * You could also filter messages based on what branch they originate from. Say all children of node 01 provide temperature data, and all children of node 02 provide humidity data.
> 
> Ultimately, you don't want to mess with the pipe addresses on network nodes because that's simply not how the library was designed.
