### ISSUE TITLE
Intermittent issue with arduino uno

### ISSUE THREAD

**Issue by dekundu** [nRF24/RF24Network#94]
Hi,
I am trying to use RF24 mesh library to create a mesh and communicate amongst the devices. 
I used two examples, a)RF24Mesh_Example_Master_To_Nodes, and b)RF24Mesh_SerialConfig. Both the devices are connected to arduino uno. Now I see a strange problem sometimes with one side. I describe it below.

In the code I am opening serial port at 9600 baud, and then printed the "Setting up master at node 0" at the very beginning. It runs fine, but when I restarted/reconnected the arduino next day, the serial output did not come correct, it showed "Setting " an then some garbled up character. Please note, between these two runs I did not change the code. Now I reset the arduino quite a few times, but found different types of garbled output. Then I restarted the pc, reconnected the arduino in usb (did not rewire the radio though). Then I loaded the getting started program with radio.printDetails() turned on. It shows radio data successfully. Then I again reloaded the Mesh master program, and found to be working.

The other arduino does not seem to have similar problem. But both works fine while using the getting started program.
My question is whatever be the case the Serial output some come correct right.
Is the arduino having some problem or the library?
Thanks
Debojit

**Comment by TMRh20** [comment]
What IDE version? If 1.6.8 please try updating it.

Sent from my iPod

On 2016-05-22, at 12:49 PM, Debojit Kundu <notifications@github.com> wrote:

Hi,
I am trying to use RF24 mesh library to create a mesh and communicate
amongst the devices.
I used two examples, a)RF24Mesh_Example_Master_To_Nodes, and
b)RF24Mesh_SerialConfig. Both the devices are connected to arduino uno. Now
I see a strange problem sometimes with one side. I describe it below.

In the code I am opening serial port at 9600 baud, and then printed the
"Setting up master at node 0" at the very beginning. It runs fine, but when
I restarted/reconnected the arduino next day, the serial output did not
come correct, it showed "Setting " an then some garbled up character.
Please note, between these two runs I did not change the code. Now I reset
the arduino quite a few times, but found different types of garbled output.
Then I restarted the pc, reconnected the arduino in usb (did not rewire the
radio though). Then I loaded the getting started program with
radio.printDetails() turned on. It shows radio data successfully. Then I
again reloaded the Mesh master program, and found to be working.

The other arduino does not seem to have similar problem. But both works
fine while using the getting started program.
My question is whatever be the case the Serial output some come correct
right.
Is the arduino having some problem or the library?
Thanks
Debojit

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/TMRh20/RF24Network/issues/94>

**Comment by dekundu** [comment]
I am using arduino 1.6.9. Is it really related to arduino version? 
I am stuck with this intermittent behavior.
Please help.

**Comment by TMRh20** [comment]
I don't think so if using 1.6.9, but I haven't had a chance to attempt to recreate. Sounds like some sort of memory issue, with the lib or the Arduino, but I'm not sure.
